config/routes.rb
Strict::Application.routes.draw do
  get "institute/dashboard"
  devise_for :universities
  resources :studies

  root :to => "home#index"
  devise_for :users
  get "devise/user"
  
  get "home/index"
  get "/student/dashboard", to: 'student#dashboard'
  get "/student/notification", to: 'student#notification'
  get "/student/profile", to: 'student#profile'
  get "/student/setting", to: 'student#setting'
  get "/student/search", to: 'student#search'
  resources :user,:university
  get "/institute/profile", to: 'institute#profile'
  get "/institute/editsettings", to: 'institute#editsettings'  

end

app/models/study.rb
class Study < ActiveRecord::Base
	belongs_to :user
end

app/models/university.rb
class University < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
   attr_accessor :login,:name
         validates :username,
  :uniqueness => {
    :case_sensitive => false
  }
  
    has_many :studies

   def studies(userid)
    return @studies=Study.where(:user_id => userid)
   end
  
  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :name) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me,:name) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :name) }
  end

  def after_sign_in_path_for(resource_or_scope)
    if(current_user)
  		student_dashboard_path
    else
      institute_dashboard_path
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
	'/home/index'
  end
   def after_sign_up_path_for(resource_or_scope)
    if(current_user)
      student_dashboard_path
    else
      institute_dashboard_path
    end
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    if(current_user)
      redirect_to student_dashboard_path
    else
      redirect_to home_index_path
    end
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
    if(current_user)
      redirect_to student_dashboard_path
    else
      redirect_to home_index_path
    end
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)
     @education.user_id=current_user.id
    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render action: 'show', status: :created, location: @education }
      else
        format.html { render action: 'new' }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:degree, :Institute, :Year, :CGPA, :Percentage)
    end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def signin
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  

  def index
  	render :layout => 'application'
  end
end

app/controllers/institute_controller.rb
class InstituteController < ApplicationController
  layout 'university'
  
  def dashboard
  @valued="active"
  @valuep=""
  @valuee=""
  end

  def editsettings
  	@valued=""
  	@valuep=""
  	@valuee="active"
  end

  def profile
  	@valued=""
  	@valuep="active"
  	@valuee=""
  end

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
layout 'student'

def dashboard
	
	@user=User.find(current_user)
	@user.studies(@user.id)
end

def profile
end

def notification
end

def search
end

def setting
end

end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]

  # GET /studies
  # GET /studies.json
  def index
    if(current_user)
      student_dashboard_path
    end
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
    if(current_user)
      student_dashboard_path
    end
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)
    @studey.user_id=current_user.id
    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render action: 'show', status: :created, location: @study }
      else
        format.html { render action: 'new' }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_params
      params.require(:study).permit(:degree, :institution, :year, :score, :SAT, :GPA)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/institute_helper.rb
module InstituteHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :degree %><br>
    <%= f.text_field :degree %>
  </div>
  <div class="field">
    <%= f.label :Institute %><br>
    <%= f.text_field :Institute %>
  </div>
  <div class="field">
    <%= f.label :Year %><br>
    <%= f.text_field :Year %>
  </div>
  <div class="field">
    <%= f.label :CGPA %><br>
    <%= f.text_field :CGPA %>
  </div>
  <div class="field">
    <%= f.label :Percentage %><br>
    <%= f.text_field :Percentage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/new.html.erb
<h1>New education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Degree:</strong>
  <%= @education.degree %>
</p>

<p>
  <strong>Institute:</strong>
  <%= @education.Institute %>
</p>

<p>
  <strong>Year:</strong>
  <%= @education.Year %>
</p>

<p>
  <strong>Cgpa:</strong>
  <%= @education.CGPA %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @education.Percentage %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>

app/views/home/_forgot_password.html.erb
<%= form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :post }) do |f| %>
<div class="modal fade" id="forgotModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel" aria-hidden="true">
			<div class="modal-dialog loginModal">
				<div class="modal-content loginContent">
					<div class="modal-header">
							<h1 class="modal-title loginHeader">Forgot your Pasword?</h1>
					</div>
					<div class="modal-body loginBody">
						<div class="container-fluid loginContainer">
							<div class="row">
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-envelope"></span>
									
									<%= f.text_field :login, :autofocus => true, :class =>"form-control tbox", :placeholder => "Email", :required => "required" %>
								</div>
								<br>
								<%= button_tag "<h4>Recover Password</h4>".html_safe, :class =>"btn btn-block buttonSignIn", :type => "submit" %>
											
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<% end %>

app/views/home/_login_form.html.erb
<div class="modal-dialog loginModal">
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  
				<div class="modal-content loginContent">
					<div class="modal-header">
						<h1 class="modal-title loginHeader">
							<span class="glyphicon glyphicon-lock"></span>Sign-In
						</h1>
					</div>
					<div class="modal-body loginBody">
						<div class="container-fluid loginContainer">
							<div class="row">
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-user"></span>
									<%= f.text_field :login, :autofocus => true, :class => "form-control tbox", :placeholder => "Email", :required => "required" %></div>
								
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-asterisk"></span>
									
  <%= f.password_field :password, :class => "form-control tbox", :placeholder => "password", :required => "required" %>
								</div>  
								<br>
								<br>
								<div class="row">
									<div class="col-xs-12 col-sm-6">
										
										<%= button_tag "<h4> Sign In </h4>".html_safe, :class =>"btn btn-block buttonSignIn", :type => "submit" %>
											
										
									</div>
									<div class="col-xs-12 col-sm-6">
										<button type="button" class="btn btn-block buttonForgotPassword" data-dismiss="modal" data-toggle="modal" data-target="#forgotModal">
											<h4>FORGOT PASSWORD</h4>
										</button>
									</div>
								</div>
								<br>
								<div class="register">
									<h3>New to Strictly Scholarship?</h3>
									<button type="button" class="btn btn-block buttonForgotPassword" data-dismiss="modal" data-toggle="modal" data-target="#registerModal">
										<h4>REGISTER</h4>
									</button>
								</div>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<h5 class="pull-left"style="color:white">OR SIGN IN WITH</h5>
						<a href="" class="btn btn-social-icon btn-facebook">
							<i class="fa fa-facebook"></i>
						</a>
						<a class="btn btn-social-icon btn-google-plus">
							<i class="fa fa-google-plus"></i>
						</a>
					</div>
				</div>
			</div>
			<% end %>

app/views/home/_registration_form.html.erb
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel" aria-hidden="true">
			<div class="modal-dialog loginModal">
				<div class="modal-content loginContent">
					<div class="modal-header">
						<h1 class="modal-title loginHeader">
							<span class="glyphicon glyphicon-pencil" ></span>Register
						</h1>
					</div>
					<div class="modal-body loginBody">
						<div class="container-fluid loginContainer">
							<div class="row">
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-user"></span>
									
									<%= f.text_field :name,:class => "form-control tbox", :placeholder => "Name", :required => "required", :autofocus => true   %>
								</div>
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-user"></span>
									
									<%= f.text_field :username, :class => "form-control tbox", :placeholder=>"Username", :required => "required" %>
								</div>
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-envelope"></span>
									
									<%= f.email_field :email, :class => "form-control tbox", :placeholder => "Email", :required=> "required"%>
								</div>
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-asterisk"></span>
									
									<%= f.password_field :password,:class => "form-control tbox", :placeholder => "Password", :required => "required"%>
								</div>
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-asterisk"></span>
									
									<%= f.password_field :password_confirmation,:class => "form-control tbox", :placeholder => "Confirm Password", :required => "required"%>
								</div>  
								<br>
								<%= button_tag "<h4> Register </h4>".html_safe, :class =>"btn btn-block buttonSignIn", :type => "submit" %>
								
								<div class="register">
									<h3>Already have an account?</h3>
									<button type="button" class="btn btn-block buttonForgotPassword" data-dismiss="modal" data-toggle="modal" data-target="#signInModal">
										<h4>Sign In</h4>
									</button>
								</div>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<h5 class="pull-left"style="color:white">OR SIGN UP WITH</h5>
						<a href="" class="btn btn-social-icon btn-facebook">
							<i class="fa fa-facebook"></i>
						</a>
						<a class="btn btn-social-icon btn-google-plus">
							<i class="fa fa-google-plus"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
		<% end %>

app/views/home/index.html.erb
<%= render :partial => "home/landing"%>

app/views/layouts/student.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Strictly Scholarship</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, maximum-scale=1.0">
			<link href="css/bootstrap.min.css" rel="stylesheet">
			<link href="css/bootstrap-social.css" rel="stylesheet">
		<script src="js/jquery.js"></script>
		<script src="js/bootstrap.min.js"></script>
			<link href="css/font-awesome.min.css" rel="stylesheet">
		<link href="css/style.css" rel="stylesheet">
		  <%= javascript_include_tag "application" %>
		  <%= stylesheet_link_tag "application", media: "all" %>
  
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
	</head>
	<body style="background-color:grey;">
		<!-- nav bar at top starts here -->
		<nav class="navbar navbar-inverse" role="navigation">
		  <div class="container">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">Strictly Scholarship</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <form class="navbar-form navbar-right" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control" placeholder="Search">
		          <button type="submit" class="btn btn-default">Submit</button>
		        </div>
		      </form>
		      <ul class="nav navbar-nav navbar-right">
		        <li><span class="label label-danger" style="font-size:12px;"><%= link_to "Logout", destroy_user_session_path, :method => :delete %></span></li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>



		<!-- the page below navbar starts -->
				
		<div class="container-fluid">
			<div class="row">
			<!-- dashboard's left pane starts here -->
				<div class="col-md-1 col-sm-1 left-sidebar pad0">
					<ul class="nav pull-right dash_ul">
						<li><%= link_to '<img src="/assets/dashboard.png"/>'.html_safe, student_dashboard_path %></li>
						<li><%= link_to '<img src="/assets/profile.png"/>'.html_safe, student_profile_path %></li>
						<li><%= link_to '<img src="/assets/notification.png"/>'.html_safe, student_notification_path %></li>
						<li><%= link_to '<img src="/assets/search.png"/>'.html_safe, student_search_path %></li>
						<li><%= link_to '<img src="/assets/setting.png"/>'.html_safe, student_setting_path %></li>
						<li><a href=""><img src="/assets/blogger.png"></a></li>
					</ul>
		  		</div>
		  	<!-- dashboard's left pane ends here -->

		  	<!-- dashboard content section starts here -->
			  	<div class="col-md-10 col-sm-10 middle-bar">
			  		<!-- margin addded here through dash_content-->
		  			<div class="row pad0 whitecolor">
		  				<div class="col-md-12">
			  				<%= yield %>
		  				</div>
       	  			</div>
		  		</div>

				<div class="col-md-1 col-sm-1 right-sidebar ">
					<!-- One can add content here as he please, the right pane  -->
				</div>
			</div>
		</div>


	</body>
</html>

app/views/layouts/university.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Strictly scholarship</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, maximum-scale=1.0">
      <link href="css/bootstrap.min.css" rel="stylesheet">
      <link href="css/bootstrap-social.css" rel="stylesheet">
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
      <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
      <%= javascript_include_tag "application" %>
        <%= stylesheet_link_tag "institute", media: "all" %>
        <%= javascript_include_tag "placement_slider.js" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body class="back">
    <div class="custom_container container-fluid  pad-clear ">

  <div class="row">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header navbar-left">
        <a class="navbar-brand" href="#l0">
         <div>
          <span class="hidden-xs">
            STRICTLY SCHOLARSHIP</span>
            <span class="visible-xs">
              Strictly Scholarship</span>

            </div>
          </a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
           <li><a href="#l5" class="navig" id="mi5">Logout</a></li>
           <li class="visible-xs <%= @valued %>"><%= link_to "Dashboard", institute_dashboard_path %></li>
           <li class="visible-xs <%= @valuep %>"><%= link_to "Profile", institute_profile_path %></li>
           <li class="visible-xs <%= @valuee %>"><%= link_to "Edit Setting", institute_editsettings_path %></li>
         </ul>
       </div><!-- /.navbar-collapse -->
     </div><!-- /.container-fluid -->
   </nav>
 </div>  <!--row-->

 <div class="row uni_row2">
  <div class="hidden-xs col-sm-2 col-sm-offset-0.5 pad-clear">
    <%= image_tag("uni_img1.jpg", :class=>"img-responsive uni_thumb pull-right") %>
  </div>
  <div class="col-xs-12 col-sm-10 uni_name pull-right">
    <span class="visible-xs text-center"><strong>
      STANFORD University </strong>
    </span>
    <span class="hidden-xs pull-right" style="color:black"><strong>
      STANFORD University </strong>
    </span>
  </div>
</div><!--uni_row2-->
<div class="row uni_row3">
  <div class="hidden-xs col-sm-1 sidebar" id="bs-navbar-collapse-1 ">
    <ul class="nav  nav-stacked animatedbgul"><h4>
      <li class="<%= @valued %>"><span><%= link_to "Dashboard", institute_dashboard_path %></span></li>
      <li class="<%= @valuep %>"><span><%= link_to "Profile", institute_profile_path %></span></li>
      <li class="<%= @valuee %>"><span><%= link_to "Edit Setting", institute_editsettings_path %></span></li></h4>
    </ul>
  </div><!--sidebar-->
    <%= yield %>
  </div>
</div>
    

  </body>
</html>

app/views/studies/edit.html.erb
<h1>Editing study</h1>

<%= render 'form' %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<h1>Listing studies</h1>

<table>
  <thead>
    <tr>
      <th>Degree</th>
      <th>Institution</th>
      <th>Year</th>
      <th>Score</th>
      <th>Sat</th>
      <th>Gpa</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @studies.each do |study| %>
      <tr>
        <td><%= study.degree %></td>
        <td><%= study.institution %></td>
        <td><%= study.year %></td>
        <td><%= study.score %></td>
        <td><%= study.SAT %></td>
        <td><%= study.GPA %></td>
        <td><%= link_to 'Show', study %></td>
        <td><%= link_to 'Edit', edit_study_path(study) %></td>
        <td><%= link_to 'Destroy', study, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study', new_study_path %>

app/views/studies/new.html.erb
<h1>New study</h1>

<%= render 'form' %>

<%= link_to 'Back', studies_path %>

app/views/studies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Degree:</strong>
  <%= @study.degree %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @study.institution %>
</p>

<p>
  <strong>Year:</strong>
  <%= @study.year %>
</p>

<p>
  <strong>Score:</strong>
  <%= @study.score %>
</p>

<p>
  <strong>Sat:</strong>
  <%= @study.SAT %>
</p>

<p>
  <strong>Gpa:</strong>
  <%= @study.GPA %>
</p>

<%= link_to 'Edit', edit_study_path(@study) %> |
<%= link_to 'Back', studies_path %>

app/views/universities/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>